repos:
  - repo: local
    hooks:
      - id: vulture
        name: vulture
        entry: vulture .
        language: python
        types: [python]
        additional_dependencies:
          - vulture==2.11

